<?php

namespace Ailixter\Gears;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-10-06 at 16:35:45.
 */
class UrlTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Url
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Url;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Ailixter\Gears\Url::clear
     * @todo   Implement testClear().
     */
    public function testClear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

//    /**
//     * @covers Ailixter\Gears\Url::set
//     * @todo   Implement testSet().
//     */
//    public function testSet()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
    /**
     * @covers Ailixter\Gears\Url::assign
     * @todo   Implement testAssign().
     */
    public function testAssign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

//    /**
//     * @covers Ailixter\Gears\Url::__get
//     * @todo   Implement test__get().
//     */
//    public function test__get()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Ailixter\Gears\Url::__isset
//     * @todo   Implement test__isset().
//     */
//    public function test__isset()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Ailixter\Gears\Url::__set
//     * @todo   Implement test__set().
//     */
//    public function test__set()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Ailixter\Gears\Url::__unset
//     * @todo   Implement test__unset().
//     */
//    public function test__unset()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }

    public function urlProvider()
    {
        return [
            ['test'],
            ['/test/1'],
            ['../test/1'],
            ['example.com/test/1?a=1&b=2'],
            ['//example.com/'],
            ['//example.com/?a=1&b=2'],
            ['//example.com/test/1?a=1&b=2'],
            ['//example.com?a=1&b=2'],
            ['http://example.com/test/1?a=1&b=2'],
            ['https://www.example.com/test/1?a=1&b=2#abc'],
            //['https://госуслуги.рф/тест/1?ж=опа#abc'],
            //['https://www.example.com/test/1?abc/123&def=456'],
        ];
    }

    /**
     * @dataProvider urlProvider
     */
    public function test__toString($test)
    {
        $this->object->set($test);
        $this->assertEquals($test, (string)$this->object);
    }

    /**
     * @covers Ailixter\Gears\Url::isValid
     * @todo   Implement testIsValid().
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
